-- Coffee MES Mockup Oracle Schema
CREATE TABLE MES_USER (
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PW VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_ROLE VARCHAR2(20) NOT NULL
);

CREATE TABLE ITEM (
    ITEM_ID VARCHAR2(30) PRIMARY KEY,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    ITEM_TYPE VARCHAR2(20) NOT NULL,
    UNIT VARCHAR2(10) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MATERIAL_STOCK (
    STOCK_ID NUMBER PRIMARY KEY,
    ITEM_ID VARCHAR2(30) NOT NULL,
    LOT_NO VARCHAR2(40),
    CURRENT_QTY NUMBER(10,2) NOT NULL,
    SAFETY_QTY NUMBER(10,2) NOT NULL,
    WAREHOUSE_NAME VARCHAR2(50),
    CONSTRAINT FK_MATERIAL_STOCK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

CREATE TABLE WORK_ORDER (
    WORK_ORDER_ID VARCHAR2(40) PRIMARY KEY,
    ITEM_ID VARCHAR2(30) NOT NULL,
    PLAN_QTY NUMBER(10,2) NOT NULL,
    WORK_DATE DATE NOT NULL,
    LINE_NAME VARCHAR2(30),
    STATUS VARCHAR2(20),
    WORKER_ID VARCHAR2(30),
    CONSTRAINT FK_WORK_ORDER_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

CREATE TABLE PRODUCTION_RESULT (
    RESULT_ID NUMBER PRIMARY KEY,
    WORK_ORDER_ID VARCHAR2(40) NOT NULL,
    TOTAL_QTY NUMBER(10,2) NOT NULL,
    GOOD_QTY NUMBER(10,2) NOT NULL,
    DEFECT_QTY NUMBER(10,2) NOT NULL,
    DEFECT_TYPE VARCHAR2(50),
    RESULT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RESULT_WORK_ORDER FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER(WORK_ORDER_ID)
);

CREATE TABLE REPORT_SNAPSHOT (
    SNAPSHOT_ID NUMBER PRIMARY KEY,
    REPORT_DATE DATE NOT NULL,
    ITEM_ID VARCHAR2(30) NOT NULL,
    PROD_QTY NUMBER(10,2),
    DEFECT_QTY NUMBER(10,2),
    SHIPMENT_QTY NUMBER(10,2),
    CONSTRAINT FK_REPORT_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
